package me.nekorainy.maigo;

public enum APIEnum {
    GET_USER_UID_BY_QRCODE_TOKEN,
    GET_USER_ACTIVITY,
    GET_USER_DATA,
    GET_USER_EXTEND_DATA,
    GET_USER_FAVORITE_ITEM,
    GET_USER_OPTION,
    GET_USER_RATING,
    GET_USER_TICKETS,
    LOGIN,
    LOGOUT,
    REQUEST_TICKET,
    UPLOAD_USER_PLAYLOG,
    GET_USER_PREVIEW
}
